# Generated by Django 5.2.3 on 2025-06-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_reservation_guest_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
