# Generated by Django 5.2.3 on 2025-06-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_reservation_reservation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_time',
            field=models.DateTimeField(),
        ),
    ]
